{
  "branches": ["main"],
  "plugins": [
    [
      "@semantic-release/commit-analyzer",
      [
        "@semantic-release/exec",
        {
          "verifyReleaseCmd": "echo \"NEXT_RELEASE_VERSION=${nextRelease.version}\""
        }
      ],
      {
        "preset": "angular",
        "releaseRules": [
          { "type": "feat", "release": "minor" },
          { "type": "refactor", "release": "patch" },
          { "type": "docs", "scope": "README", "release": "patch" },
        ],
        "parserOpts": {
          "noteKeywords": ["BREAKING CHANGE", "BREAKING CHANGES"]
        }
      }
    ],
    "@semantic-release/release-notes-generator"
  ]
}