name: delivery

on:
  push:
    branches: [ "main" ]

jobs:
  delivery:
    runs-on: [ ubuntu-latest ]
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: 'true'

    - name: Print head git commit message
      run: |
        echo "${{github.event.head_commit.message}}"

    - name: print tags
      run: |
        echo "$(git for-each-ref --sort=-creatordate --format '%(refname)' refs/tags)"

    - name: print last tag
      id: last-tag
      run: |
        echo "$(git describe --tags --abbrev=0 --match="v[0-9].[0-9].[0-9]*" HEAD)"
        echo "current_version=$(git describe --tags --abbrev=0 --match="v[0-9].[0-9].[0-9]*" HEAD)" >> "$GITHUB_OUTPUT"

    - name: Print if it is a feature
      if: ${{ contains(github.event.head_commit.message, 'feat:') }}
      run: |
        echo "it was a feature"
        ./versioning.sh ${{ steps.last-tag.outputs.current_version }} 1

    - name: Print if it is a fix
      if: ${{ contains(github.event.head_commit.message, 'fix:') }}
      run: |
        echo "it was a feature"
        ./versioning.sh ${{ steps.last-tag.outputs.current_version }} 2
