name: quality

on:
  pull_request:
    branches: [ "main" ]

jobs:
  quality:
    runs-on: [ ubuntu-latest ]
    steps:
    - name: checkout
      uses: actions/checkout@v3
            
    - name: Conventional Commit Linter
      uses: ahmadnassri/action-commit-lint@v2

    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          src:
            - 'cmd/**'
            - 'internal/**'
          docker:
            - 'Dockerfile'
          docs:
            - 'README.md'
            - 'docs/**'
    
    - name: Dockerfile Linter
      if: steps.changes.outputs.docker == 'true'
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ./Dockerfile

    - name: Setup go
      if: steps.changes.outputs.src == 'true'
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Cache Go Build
      if: steps.changes.outputs.src == 'true'
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-basic-micro-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-basic-micro-
    
    - name: Scan for Vulnerabilities in Code
      if: steps.changes.outputs.src == 'true'
      uses: Templum/govulncheck-action@v1.0.0
      with:
        go-version: '1.21'
        skip-upload: true

    - name: install go vuln check
      if: steps.changes.outputs.src == 'true'
      run: go install golang.org/x/vuln/cmd/govulncheck@latest
    
    - name: Run govulncheck
      if: steps.changes.outputs.src == 'true'
      run: govulncheck -test ./...

    - name: Go Test
      if: steps.changes.outputs.src == 'true'
      run: make test
